name = input ("what is your name friend")
print (f"Hi {name}!")
print ("Wow thats a nice name!")
print ("What is your last name?")
input ("")
print ("Intresting! Thats elegant and fancy!")
print ("Now for why your here...... DO YOU LIKE SNAKES?")
input ("")
print ("Mmmm ok... ok...OKAY! so you absolutely love snakes I hear!")
print ("well did you know snakes smell using their tongue?")
input ("")
print ("Yes, you did know that...oh OK")
print ("well I bet you didn't know this: According to The Nature Conservancy Did you know that Lyme disease is less prevalent when rattlesnakes are abundant?") 
print ("did you know that hmm?")
input ("")
print ("YES! I got you, you didn't know that! heh, you may go now")
input ("")
print ("bye now, I hope you like snakes even more now")